# Generated by Django 5.1.6 on 2025-02-25 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_github_user_telegram_user_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='github',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='user',
            name='website',
            field=models.CharField(default='', max_length=128),
        ),
    ]
