# Generated by Django 5.1.6 on 2025-02-20 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('link', models.CharField(max_length=512)),
                ('imdage', models.ImageField(upload_to='project_iamges')),
                ('description', models.TextField()),
                ('technology_owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='technology.technology')),
            ],
        ),
    ]
