# Generated by Django 5.1.6 on 2025-02-21 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technology', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='imdage',
        ),
        migrations.CreateModel(
            name='ProjectImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='project_iamges')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='technology.technology')),
            ],
        ),
    ]
