# Generated by Django 5.1.6 on 2025-02-21 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technology', '0002_remove_project_imdage_projectimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectimages',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='technology.project'),
        ),
    ]
