# Generated by Django 5.1.6 on 2025-02-28 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technology', '0005_technology_owner_alter_project_technology_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technology',
            name='name',
            field=models.CharField(max_length=32),
        ),
    ]
